# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raum für ihr Recht
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://ruge.niels-nuebel.de"
googleanalyticss:  UA-XXXXX-1

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME]
sass:
  sass_dir: _sass
  style: compressed

repository: nielsnuebel/ruge

# Site nav
nav:

- name: Home
  link: "/"

- name: VITA
  link: "#vita"

- name: Kanzleischwerpunkt
  link: "#schwerpunkte"

- name: Leistungskatalog
  link: "#leistungen"

- name: Veröffentlichungen
  link: "#veroeffentlichungen"

- name: Kontakt
  link: "#kontakt"



